"""Layer 1 E2E tests — real components, stub servers, no mocks.

These tests wire the real GristClient (with real httpx HTTP calls) to an
in-process Grist stub server, use real Message objects (signalbot dataclass),
and run real strategy YAML pipelines through the ReactCommand handler.

The only mock is the bot object on the Context (since the Signal reaction
HTTP call is tested in Layer 2 with Docker). Everything else is real.

Value over existing unit/integration tests:
  - GristClient makes real HTTP requests (not mocked AsyncMock)
  - SQL queries are captured by the stub and asserted on
  - Message objects are real signalbot dataclass instances
  - httpx error paths are tested with real HTTP error responses
"""

import asyncio
from unittest.mock import AsyncMock, MagicMock

import pytest

pytestmark = pytest.mark.e2e

from bot.commands import RateLimiter, ReactCommand
from signalbot.context import Context
from signalbot.message import Message, MessageType

from .conftest import BOT_UUID, SENDER_NUMBER, SENDER_UUID

# Exact SQL strings generated by YamlStrategy (LOWER() wrapping, no identifier quoting)
STOCK_SQL = "SELECT in_stock FROM Products WHERE LOWER(name) = ?"
ORDER_SQL = "SELECT status FROM Orders WHERE LOWER(order_id) = ?"


# --- Helpers ---


def _make_message(
    text,
    *,
    group=None,
    mentions=None,
    source=SENDER_NUMBER,
    source_uuid=SENDER_UUID,
    timestamp=1700000000000,
):
    """Construct a real signalbot Message (dataclass, not a mock)."""
    return Message(
        source=source,
        source_number=source,
        source_uuid=source_uuid,
        timestamp=timestamp,
        type=MessageType.DATA_MESSAGE,
        text=text,
        group=group,
        mentions=mentions or [],
    )


def _make_context(message):
    """Wrap a real Message in a Context with a mock bot (for react capture)."""
    bot = MagicMock()
    bot.react = AsyncMock()
    return Context(bot, message)


def _run(coro):
    """Run an async coroutine in the current event loop."""
    return asyncio.get_event_loop().run_until_complete(coro)


# =============================================================================
# Stock check — full pipeline with real HTTP
# =============================================================================


class TestStockCheckE2E:
    """End-to-end: message -> strategy -> real HTTP to Grist stub -> reaction."""

    def test_stock_in_stock_reacts_check(self, grist_stub, grist_client, stock_strategy):
        """'stock Bandages' with in_stock=1 -> reacts with checkmark."""
        grist_stub.set_response(STOCK_SQL, [{"in_stock": 1}])

        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message("stock Bandages")
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        ctx.bot.react.assert_awaited_once_with(msg, "\u2705")

        # Verify the SQL query sent over HTTP
        assert len(grist_stub.captured_queries) == 1
        q = grist_stub.captured_queries[0]
        assert q.sql == STOCK_SQL
        assert q.args == ["bandages"]

    def test_stock_out_of_stock_reacts_prohibited(
        self, grist_stub, grist_client, stock_strategy
    ):
        """'stock Unobtanium' with in_stock=0 -> reacts with prohibited sign."""
        grist_stub.set_response(STOCK_SQL, [{"in_stock": 0}])

        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message("stock Unobtanium")
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        ctx.bot.react.assert_awaited_once_with(msg, "\U0001F6AB")
        q = grist_stub.captured_queries[0]
        assert q.args == ["unobtanium"]

    def test_stock_not_found_reacts_question(
        self, grist_stub, grist_client, stock_strategy
    ):
        """'stock Widgets' with no rows -> reacts with question mark."""
        grist_stub.set_response(STOCK_SQL, [])

        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message("stock Widgets")
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        ctx.bot.react.assert_awaited_once_with(msg, "\u2753")

    def test_unmatched_message_no_query(
        self, grist_stub, grist_client, stock_strategy
    ):
        """A message that doesn't match any rule sends no query."""
        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message("hello world")
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        assert len(grist_stub.captured_queries) == 0
        ctx.bot.react.assert_not_awaited()


# =============================================================================
# Order status — different strategy, same pipeline
# =============================================================================


class TestOrderStatusE2E:
    def test_order_shipped(self, grist_stub, grist_client, order_strategy):
        grist_stub.set_response(ORDER_SQL, [{"status": "shipped"}])

        cmd = ReactCommand(
            db=grist_client, strategy=order_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message("order 12345")
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        ctx.bot.react.assert_awaited_once_with(msg, "\U0001F4E6")
        assert grist_stub.captured_queries[0].args == ["12345"]  # already lowercase

    def test_order_not_found(self, grist_stub, grist_client, order_strategy):
        grist_stub.set_response(ORDER_SQL, [])

        cmd = ReactCommand(
            db=grist_client, strategy=order_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message("order 99999")
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        ctx.bot.react.assert_awaited_once_with(msg, "\u2753")


# =============================================================================
# Group chat with @-mentions — real Message with mentions field
# =============================================================================


class TestGroupMentionE2E:
    def test_mentioned_in_group_processes(
        self, grist_stub, grist_client, stock_strategy
    ):
        """Bot is @-mentioned in a group -> message is processed."""
        grist_stub.set_response(STOCK_SQL, [{"in_stock": 1}])

        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message(
            "\uFFFC stock Bandages",
            group="group.TestGroupId12345678901234567890123456789012345678901234567=",
            mentions=[{"uuid": BOT_UUID, "start": 0, "length": 1}],
        )
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        ctx.bot.react.assert_awaited_once_with(msg, "\u2705")
        # Verify the placeholder was stripped before querying
        assert grist_stub.captured_queries[0].args == ["bandages"]

    def test_not_mentioned_in_group_ignored(
        self, grist_stub, grist_client, stock_strategy
    ):
        """No @-mention in group -> message ignored, no Grist query."""
        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message(
            "stock Bandages",
            group="group.TestGroupId12345678901234567890123456789012345678901234567=",
            mentions=[],
        )
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        assert len(grist_stub.captured_queries) == 0
        ctx.bot.react.assert_not_awaited()

    def test_someone_else_mentioned_ignored(
        self, grist_stub, grist_client, stock_strategy
    ):
        """A different user @-mentioned in group -> ignored."""
        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message(
            "\uFFFC stock Bandages",
            group="group.TestGroupId12345678901234567890123456789012345678901234567=",
            mentions=[{"uuid": "other-user-uuid", "start": 0, "length": 1}],
        )
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        assert len(grist_stub.captured_queries) == 0
        ctx.bot.react.assert_not_awaited()


# =============================================================================
# Rate limiting — real RateLimiter with real HTTP pipeline
# =============================================================================


class TestRateLimitE2E:
    def test_rate_limited_sender_dropped(
        self, grist_stub, grist_client, stock_strategy
    ):
        """After exceeding the limit, messages are silently dropped."""
        grist_stub.set_response(STOCK_SQL, [{"in_stock": 1}])

        limiter = RateLimiter(max_messages=2, window_seconds=60)
        cmd = ReactCommand(
            db=grist_client,
            strategy=stock_strategy,
            bot_uuid=BOT_UUID,
            rate_limiter=limiter,
        )

        # First two messages succeed
        for i in range(2):
            msg = _make_message("stock Bandages", timestamp=1700000000000 + i)
            ctx = _make_context(msg)
            _run(cmd.handle(ctx))
            ctx.bot.react.assert_awaited_once()

        # Third message is rate-limited — no query, no reaction
        grist_stub.captured_queries.clear()
        msg = _make_message("stock Bandages", timestamp=1700000000002)
        ctx = _make_context(msg)
        _run(cmd.handle(ctx))
        ctx.bot.react.assert_not_awaited()
        assert len(grist_stub.captured_queries) == 0

    def test_different_senders_independent(
        self, grist_stub, grist_client, stock_strategy
    ):
        """Rate limits are per-sender — one sender's limit doesn't block another."""
        grist_stub.set_response(STOCK_SQL, [{"in_stock": 1}])

        limiter = RateLimiter(max_messages=1, window_seconds=60)
        cmd = ReactCommand(
            db=grist_client,
            strategy=stock_strategy,
            bot_uuid=BOT_UUID,
            rate_limiter=limiter,
        )

        # sender-1 uses their allowance
        msg1 = _make_message("stock Bandages", source_uuid="sender-1")
        ctx1 = _make_context(msg1)
        _run(cmd.handle(ctx1))
        ctx1.bot.react.assert_awaited_once()

        # sender-2 is unaffected
        msg2 = _make_message("stock Bandages", source_uuid="sender-2")
        ctx2 = _make_context(msg2)
        _run(cmd.handle(ctx2))
        ctx2.bot.react.assert_awaited_once()

        # sender-1 is blocked
        msg3 = _make_message("stock Bandages", source_uuid="sender-1")
        ctx3 = _make_context(msg3)
        _run(cmd.handle(ctx3))
        ctx3.bot.react.assert_not_awaited()


# =============================================================================
# Grist error handling — real HTTP 500 response
# =============================================================================


class TestGristErrorE2E:
    def test_grist_500_does_not_crash(
        self, grist_stub, grist_client, stock_strategy
    ):
        """A Grist HTTP 500 is handled gracefully — no reaction, no crash."""
        grist_stub.set_error(STOCK_SQL)

        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message("stock Bandages")
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        ctx.bot.react.assert_not_awaited()
        # The query was still sent (and rejected by the stub)
        assert len(grist_stub.captured_queries) == 1

    def test_grist_recovers_after_error(
        self, grist_stub, grist_client, stock_strategy
    ):
        """After a Grist error, subsequent requests still work."""
        # First call errors
        grist_stub.set_error(STOCK_SQL)
        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg1 = _make_message("stock Bandages")
        ctx1 = _make_context(msg1)
        _run(cmd.handle(ctx1))
        ctx1.bot.react.assert_not_awaited()

        # Remove error, set normal response
        grist_stub._error_sqls.discard(STOCK_SQL)
        grist_stub.set_response(STOCK_SQL, [{"in_stock": 1}])

        msg2 = _make_message("stock Bandages")
        ctx2 = _make_context(msg2)
        _run(cmd.handle(ctx2))
        ctx2.bot.react.assert_awaited_once_with(msg2, "\u2705")


# =============================================================================
# Empty / edge-case messages with real components
# =============================================================================


class TestEdgeCasesE2E:
    def test_empty_message_no_query(self, grist_stub, grist_client, stock_strategy):
        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message("")
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        assert len(grist_stub.captured_queries) == 0
        ctx.bot.react.assert_not_awaited()

    def test_none_message_no_query(self, grist_stub, grist_client, stock_strategy):
        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message(None)
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        assert len(grist_stub.captured_queries) == 0
        ctx.bot.react.assert_not_awaited()

    def test_mention_only_placeholder_no_query(
        self, grist_stub, grist_client, stock_strategy
    ):
        """A group message with only the mention placeholder and no text."""
        cmd = ReactCommand(
            db=grist_client, strategy=stock_strategy, bot_uuid=BOT_UUID
        )
        msg = _make_message(
            "\uFFFC",
            group="group.TestGroupId12345678901234567890123456789012345678901234567=",
            mentions=[{"uuid": BOT_UUID, "start": 0, "length": 1}],
        )
        ctx = _make_context(msg)

        _run(cmd.handle(ctx))

        assert len(grist_stub.captured_queries) == 0
        ctx.bot.react.assert_not_awaited()
